version: '3'

services:
  python-etl:
    build: .
    privileged: true
    ports:
      - 8081:5000
    depends_on:
      - db
    volumes:
      - ${PWD}:/app
  
  db:
    container_name: mysql_container
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3308"
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
  
  # adminer:    
  #   image: dockette/adminer:full-php5
  #   ports:      
  #     - "8084:8080"
  # volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local
  