version: '3'

services:
  python-etl:
    build: .
    privileged: true
    ports:
      - 8081:5000
    depends_on:
      - database
    volumes:
      - ${PWD}:/app
  
  database:
    container_name: mycontainername
    image: mysql/mysql-server:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8084:8080"